### ISSUE TITLE
[bug report] FF `imageset` erroneously categorised `other` as opposed to `image`

### ISSUE THREAD

**Issue by n8v8R** [schomery/policy-control#16]
PC 0.3.3 FF 56/58/59 on Win 7 64bit

having  `image`  set to `allow all` and `other resources` to `block all` img element tags showing in the PC log as blocked like this one

`other 	https://blog.mozilla.org/addons/files/2017/11/image3.png`

the governing html code reads:

`<img src="https://blog.mozilla.org/addons/files/2017/11/image3.png" alt="https://blog.mozilla.org/addons/files/2017/11/image3.png">`

**Comment by schomery** [comment]
This seems like a bug in Firefox webRequest API. To confirm try the same page on Google Chrome and you will see those requests in the `image` category! Please report this to Bugzilla.

**Comment by n8v8R** [comment]
Thanks for the feedback. Whilst I would not mind to open a bug on Mozilla's Bugzilla I have admittedly no clue how the webRequest API is working and thus would not really know how to phrase/describe it.

**Comment by n8v8R** [comment]
Strange/curious thing is that it seems to happen only with Mozilla sites, have not yet come across any other occurance

**Comment by n8v8R** [comment]
Did some digging based on the comparison with Chrome you suggested. What became apparent is that PC is actually categorising `imageset` (FF showing as **cause** tab in the FF network console) as `other` as opposed to `image`. In the Chrome network console there no such cause and thus no `imageset`.

Would appreciate if that could be sorted/remedied somehow for FF.

**Comment by n8v8R** [comment]
Any intention to fix this? It is rather detrimental to the usefulness of the add-on.

**Comment by morues** [comment]
> In the Chrome network console there no such cause and thus no imageset.

Sorry for the late fix. Should have been resolved on 0.3.5

**Comment by ghost** [comment]
No worries, I am just very happy that you did as I appreciate this add-on very much.

I would hope that you not miss the [other issue,](https://github.com/schomery/policy-control/issues/15) despite you closed it last  time as fixed, did not fix however in full
